export const GET_TOPICS = "GET_TOPICS";
export const LOADING_TOPICS = "LOADING_TOPICS";
export const GET_ONE_TOPIC = "GET_ONE_TOPIC";
export const POST_ONE_TOPIC = "POST_ONE_TOPIC";
export const DELETE_ONE_TOPIC = "DELETE_ONE_TOPIC";

export const GET_ONE_COMMENT = "GET_ONE_COMMENT";
export const GET_COMMENTS = "GET__COMMENTS";
export const LOADING_COMMENTS = "LOADING_COMMENTS";
export const POST_ONE_COMMENT = "POST_ONE_COMMENT";
export const DELETE_ONE_COMMENT = "DELETE_ONE_COMMENT"

export const GET_ONE_USER = "GET_ONE_USER";
export const LOADING_USERS = "LOADING_USERS";


export const POST_ONE_REPLY = "POST_ONE_REPLY";
